<?php

namespace App\Http\DataTable\Controllers;

use App\App\Controllers\Controller;
use App\App\Controllers\DataTableAbstract;
use App\Domain\System\Menu\Menu;
use Illuminate\Http\Request;

class MenuDataTableController extends DataTableAbstract
{
    public function getRecords()
    {
        return Menu::with('parent')->get(); // TODO: Change the autogenerated stub
    }

    public function map($record): array
    {
        return [
            ($record->icon != '')? '<i class="fas '.$record->icon.'"></i>': '',
            $record->name,
            $record->route,
            optional($record->parent)->name,
            $this->getOptionButtons($record->id)
        ];
    }
}
